blank_issues_enabled: false
contact_links:
    - name: ❗️ All other issues or Q&A
      url: https://github.com/bralandealmeida/infosimples-sdk/discussions
      about: |
          Please use GitHub Discussions for other issues and asking questions.
